### PR TITLE
fix: fixed navbar on all devices #693

### PR DESCRIPTION
**Pull request by kingdanie**
## Describe your changes
made navbar fixed for all devices

## Issue ticket number and link
closed issue #693

## Motivation and Context
Make the navbar also fixed on mobile devices.

### CODE REVIEW

**Comment by kingdanie** [comment]
@ijemmao  for some reason the class "fixed" was not giving the desired result, therefore as a hack I implemented it as an inline style . Hope this is ok?

**Comment by ijemmao** [comment]
@kingdanie did you attempt to use the TAILWIND CSS fixed class? That should do the trick

**Comment by kingdanie** [comment]
or could it have something to do with the tailwind config file?

it might not be related, but I just read from the tailwind docs that the **purge** property in the config file should be changed to **content**  when using v3. https://tailwindcss.com/docs/upgrade-guide#configure-content-sources

**Comment by ijemmao** [comment]
> or could it have something to do with the tailwind config file?
> 
> it might not be related, but I just read from the tailwind docs that the **purge** property in the config file should be changed to **content** when using v3. https://tailwindcss.com/docs/upgrade-guide#configure-content-sources

that does seem related, but we do have the `content` field within `tailwind.config.js` so if anything the `purge` field should be ignored 😕 

did you attempt to run `yarn build` to build the project and then `yarn start`? that will build the project just like in production and you can see if the styles get applied there - if not, we can revert back to your initial approach and then create a follow up issue to address this

**Comment by kingdanie** [comment]
yeah, that was exactly the issue I forgot to build after making the change. I however noticed it and added the tailwind class instead of the inline style in my last commit.

**Comment by ijemmao** [comment]
@kingdanie for visual changes, can you please attach a video of this change working as expected on mobile?

**Comment by kingdanie** [comment]
sure

**Comment by kingdanie** [comment]
Screenshot 2023-07-01 at 15 24 20

**Pull request merged**
