### PR TITLE
change filename and add type definition to app

### PR DESCRIPTION
**Pull request by jibranabsarulislam**
hi! my first PR (hopefully of many) for this repo. thank you for creating this project and accepting contributions!

## Describe your changes
- Change filename from `app.js` to `app.ts`
- Add `Express` type definition for `app`

## Issue ticket number and link
#650 

## Motivation and Context
Using static type definitions in javascript can contribute to more type-checking and validation during development.

## How Has This Been Tested?
This is where I wanted to inquire! ~~I did not setup the project locally (yet)~~ I'm running on Windows 10 and noticed that the scripts incorporate Mac/UNIX syntax (i.g. `start:database` using `&>/dev/null`), but given that imports do not depend on file extensions, #650 requires a filename change and type definition for `app`

I'll setup the fork on Ubuntu and hopefully all goes well 

## Screenshots (if appropriate):
N/A

please let me know of any requested changes, and I'll resolve them appropriately 🙌

### CODE REVIEW

**Comment by ijemmao** [comment]
@jibranabsarulislam these changes all look great! just as a source of confirmation that this doesn't break anything (i don't think it does break anything) can you attach a screenshot of the Jest tests passing locally? Our CI pipeline doesn't play nice with the fact that this project uses Firebase - I would love to have that fixed in the future, but for now a screenshot of passing tests will do the trick 😊

**Review by ijemmao — APPROVED** [review]
looks great! just awaiting the screenshots of passing tests

**Comment by jibranabsarulislam** [comment]
thank you @ijemmao!
I'll revisit the tests in the morning; can you give me a hint as to why a lot of tests fail? it looks like my local mongodb might not have been setup correctly, although I see the documents in the `igbo_api` and `test_igbo_api` collections. below are the errors i've come across

---

This warning is frequent: `{"severity":"WARNING","message":"Warning, FIREBASE_CONFIG and GCLOUD_PROJECT environment variables are missing. Initializing firebase-admin will fail"}`

---

I've tried `yarn migrate-up`, but it fails with module error `MongoServerError: BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'`

---

this is my output of `yarn jest 2>&1 | grep '●'`

image

**Comment by ijemmao** [comment]
@jibranabsarulislam that's interesting - can you just try running `yarn start:database` in one terminal and then run `yarn jest` that's enough to run the tests - i'll have to update the docs to make this known! thanks for sharing this

**Comment by ijemmao** [comment]
@jibranabsarulislam if it still doesn't work locally after running those two commands, we can merge this PR after I test the changes locally as a sanity check and then you can open up a new issue in this repo so i can take a look at this

**Comment by jibranabsarulislam** [comment]
unfortunately I got the same count & errors

image

I'll keep an eye out for if this gets merged and draft an issue with my steps and output. thanks again @ijemmao

**Comment by ijemmao** [comment]
@jibranabsarulislam great work! i really want to fix our testing pipeline for contributors to make this process easier - can you create an issue detailing the blockers you experienced with running tests locally and i can address it in the near future? thanks for your amazing contributions ✨

**Comment by jibranabsarulislam** [comment]
thanks a ton @ijemmao! i've opened an issue #656 regarding the problem and full steps. i'm looking forward to the resolution and future contributions!

**Pull request merged**
