### PR TITLE
Fix failing cypress tests

### LINKED ISSUE #773: Failing cypress tests
**Describe the bug**
Some test cases fail when running `npm run cypress:run` on local and GitHub actions

**To Reproduce**
1. Setup local development
2. Run `npm run cypress:run` 

**Expected behavior**
All cypress tests should pass

**Screenshots**
Screenshot 2024-03-07 at 07 07 21

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 122.0.6261.94

**Smartphone (please complete the following information):**
 N/A

### PR DESCRIPTION
**Pull request by sir-radar**
## Describe your changes
Changes/Improvements to cypress test code to cater for new changes causing pipeline failures

## Issue ticket number and link
Closed #773 

## Motivation and Context
Resolve pipeline failure.

## How Has This Been Tested?
Run `npm run cypress:run`

### CODE REVIEW

**Comment by sir-radar** [comment]
@ijemmao please take a look

**Review by ijemmao — COMMENTED** [review]
@sir-radar can you include an image of the frontend Cypress tests locally passing on your machine in your PR description?

**Comment by sir-radar** [comment]
@ijemmao I noticed another issue making some Cypress tests fail, I have created issue  #776 to resolve it.

**Review by ijemmao — APPROVED** [review]
great! we can follow up in your new issue ticket - amazing work

**Pull request merged**
